spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:2881/ai_baby?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
nlp:
  api-key: ${QWEN_API_KEY}
  url: ${QWEN_BASE_URL}
