server:
  port: 8080

spring:
  application:
    name: sql-agent

  datasource:
    url: jdbc:mysql://127.0.0.1:2881/ai_baby?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    com.ai.baby.sqlagent: DEBUG
    dev.langchain4j: DEBUG
    dev.langchain4j.service: DEBUG
    # dev.langchain4j.model.openai: TRACE

llm:
  provider: qwen
  base-url: https://ws-4pen9k08h2xt0ui0.cn-beijing.maas.aliyuncs.com/compatible-mode/v1
  api-key: sk-ws-H.RXLDEDR.1F8w.MEQCIF89aNIXmwqmcGsn__9h4ByqGx6DcBuStoaJPLtGK0BjAiBSSLqkuVRr8FrZk5J93O9S060D9R78ZBaobaIXfLPkJQ
  model: qwen-plus
  temperature: 0.0
  timeout: 60